class StachV3SchemaProperties:
    Name = "name"
    Version = "version"
    Columns = "columns"
    Rows = "rows"
    Table = "table"
    MultiLevelHeadersTable = "multiLevelHeadersTable"
    Views = "views"
    Headers = "headers"
    GroupResult = "groupResult"
    SplitResult = "splitResult"
    PrimaryKeys = "primaryKeys"
    TotalNumRows = "totalNumRows"
    MultiLevelHeadersTableReference = "multiLevelHeadersTableReference"